// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using FlexBackend.Infra.Models;
using System;
using System.Collections.Generic;

namespace FlexBackend.Core.DTOs.PROD;

/// <summary>
/// 商品基本資料
/// </summary>
public partial class ProdProductQueryDto
{
    /// <summary>
    /// 商品ID
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// 供應商ID(FK)
    /// </summary>
    public int SupplierId { get; set; }

    /// <summary>
    /// 品牌ID
    /// </summary>
    public int? BrandId { get; set; }

    /// <summary>
    /// 商品名稱
    /// </summary>
    public string ProductName { get; set; }

    /// <summary>
    /// 商品簡短描述，常用於列表展示
    /// </summary>
    public string ShortDesc { get; set; }

    /// <summary>
    /// 商品完整描述，用於詳細頁
    /// </summary>
    public string FullDesc { get; set; }

    /// <summary>
    /// 是否上架（0=否，1=是）
    /// </summary>
    public bool IsPublished { get; set; }

    /// <summary>
    /// 重量（公斤）
    /// </summary>
    public decimal? Weight { get; set; }

    /// <summary>
    /// 體積
    /// </summary>
    public decimal? VolumeCubicMeter { get; set; }

    /// <summary>
    /// 體積單位
    /// </summary>
    public string VolumeUnit { get; set; }

    /// <summary>
    /// SKU清單
    /// </summary>
    public List<ProdProductSkuDto> Skus { get; set; } = new();

    /// <summary>
    /// 照片清單
    /// </summary>
    public List<ProdProductImageDto> Images { get; set; } = new();

    /// <summary>
    /// 分類清單
    /// </summary>
    public List<ProdProductTypeDto> Types { get; set; } = new();

    /// <summary>
    /// 規格清單
    /// </summary>
    public List<ProdSpecificationConfigDto> SpecConfigs { get; set; } = new();

    /// <summary>
    /// 規格選項清單
    /// </summary>
    public List<ProdSpecificationOptionDto> SpecOptions { get; set; } = new();

    /// <summary>
    /// 屬性選項清單
    /// </summary>
    public List<ProdAttributeOptionDto> AttributeOptions { get; set; } = new();

    /// <summary>
    /// 組合清單
    /// </summary>
    public List<ProdBundleItemDto> BundleItems { get; set; } = new();

    /// <summary>
    /// 成分清單
    /// </summary>
    public List<ProdProductIngredientDto> Ingredients { get; set; } = new();
}