// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Core.DTOs.PROD;

/// <summary>
/// 套組明細表：記錄套組內有哪些子商品
/// </summary>
public partial class ProdBundleItemDto
{
    /// <summary>
    /// 套組ID (FK)
    /// </summary>
    public int BundleId { get; set; }

    /// <summary>
    /// 商品ID (FK)
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// 套組名稱
    /// </summary>
    public string BundleName { get; set; }
}