// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 自動回覆規則
/// </summary>
public partial class CsAutoReplyRule
{
    /// <summary>
    /// 規則主鍵
    /// </summary>
    public int RuleId { get; set; }

    /// <summary>
    /// 規則名稱（管理用）
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 1=關鍵字、2=正則、3=預設回覆
    /// </summary>
    public int MatchType { get; set; }

    /// <summary>
    /// 優先序（小在前）
    /// </summary>
    public int Priority { get; set; }

    /// <summary>
    /// 最低信心分數（0~1）
    /// </summary>
    public decimal MinConfidence { get; set; }

    /// <summary>
    /// 1=導向FAQ、2=文字、3=連結、4=轉人工/表單
    /// </summary>
    public int ResponseType { get; set; }

    /// <summary>
    /// 回覆文字（對應 2）
    /// </summary>
    public string ResponseText { get; set; }

    /// <summary>
    /// 對應 FAQ（對應 1）
    /// </summary>
    public int? ResponseFaqId { get; set; }

    /// <summary>
    /// 導向連結（對應 3）
    /// </summary>
    public string ResponseUrl { get; set; }

    /// <summary>
    /// 是否啟用
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// 建檔時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual ICollection<CsChatMessage> CsChatMessage { get; set; } = new List<CsChatMessage>();

    public virtual CsFaq ResponseFaq { get; set; }
}