// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 行銷優惠券設定（引用規則分類檔）
/// </summary>
public partial class MktCoupon
{
    /// <summary>
    /// 優惠券Id
    /// </summary>
    public int CouponId { get; set; }

    /// <summary>
    /// 關聯活動Id
    /// </summary>
    public int CampaignId { get; set; }

    /// <summary>
    /// 關聯規則Id
    /// </summary>
    public int RuleId { get; set; }

    /// <summary>
    /// 優惠券名稱
    /// </summary>
    public string CouponName { get; set; }

    /// <summary>
    /// 優惠券代碼
    /// </summary>
    public string CouponCode { get; set; }

    /// <summary>
    /// 狀態（有效、停用）
    /// </summary>
    public string Status { get; set; }

    /// <summary>
    /// 發放開始日期
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>
    /// 發放結束日期
    /// </summary>
    public DateTime? EndDate { get; set; }

    /// <summary>
    /// 折扣金額
    /// </summary>
    public decimal? DiscountAmount { get; set; }

    /// <summary>
    /// 折扣百分比
    /// </summary>
    public decimal? DiscountPercent { get; set; }

    /// <summary>
    /// 總發放數量
    /// </summary>
    public int TotQty { get; set; }

    /// <summary>
    /// 剩餘數量
    /// </summary>
    public int LeftQty { get; set; }

    /// <summary>
    /// 每人可領取上限
    /// </summary>
    public int UserLimit { get; set; }

    /// <summary>
    /// 有效時長（小時）
    /// </summary>
    public int ValidHours { get; set; }

    /// <summary>
    /// 是否啟用（0=否,1=是）
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// 建檔人員
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 建檔時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    public virtual MktCampaign Campaign { get; set; }

    public virtual ICollection<OrdOrder> OrdOrder { get; set; } = new List<OrdOrder>();

    public virtual ICollection<OrdOrderAdjustment> OrdOrderAdjustment { get; set; } = new List<OrdOrderAdjustment>();

    public virtual MktCouponRule Rule { get; set; }

    public virtual ICollection<UserCouponWallet> UserCouponWallet { get; set; } = new List<UserCouponWallet>();
}