// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 發票
/// </summary>
public partial class OrdInvoice
{
    /// <summary>
    /// 發票ID
    /// </summary>
    public int InvoiceId { get; set; }

    /// <summary>
    /// 訂單編號（FK）
    /// </summary>
    public int OrderId { get; set; }

    /// <summary>
    /// 發票號碼；唯一
    /// </summary>
    public string InvoiceNo { get; set; }

    /// <summary>
    /// 買受人
    /// </summary>
    public string BuyerName { get; set; }

    /// <summary>
    /// 統編8碼
    /// </summary>
    public string TaxId { get; set; }

    /// <summary>
    /// 載具號碼
    /// </summary>
    public string CarrierNo { get; set; }

    /// <summary>
    /// 發票金額
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// 狀態
    /// </summary>
    public string Status { get; set; }

    /// <summary>
    /// 開立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 更新時間（；更新時改寫）
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    /// <summary>
    /// 作廢原因
    /// </summary>
    public string VoidReason { get; set; }

    /// <summary>
    /// 折讓單號
    /// </summary>
    public string AllowanceRef { get; set; }

    public virtual OrdOrder Order { get; set; }
}