// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 訂單明細
/// </summary>
public partial class OrdOrderItem
{
    /// <summary>
    /// 訂單明細編號
    /// </summary>
    public int OrderItemId { get; set; }

    /// <summary>
    /// 訂單編號（FK）
    /// </summary>
    public int OrderId { get; set; }

    /// <summary>
    /// 商品編號（對照表後補）
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// 貨號(退貨動庫存用)
    /// </summary>
    public int SkuId { get; set; }

    /// <summary>
    /// 單價
    /// </summary>
    public decimal UnitPrice { get; set; }

    /// <summary>
    /// 數量；建議CHECK：&gt; 0
    /// </summary>
    public int Qty { get; set; }

    public virtual ICollection<OrdOrderItemAdjustment> OrdOrderItemAdjustment { get; set; } = new List<OrdOrderItemAdjustment>();

    public virtual ICollection<OrdReturnItem> OrdReturnItem { get; set; } = new List<OrdReturnItem>();

    public virtual OrdOrder Order { get; set; }

    public virtual ProdProduct Product { get; set; }

    public virtual ProdProductSku Sku { get; set; }

    public virtual ICollection<SupStockHistory> SupStockHistory { get; set; } = new List<SupStockHistory>();
}