// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 退貨明細
/// </summary>
public partial class OrdReturnItem
{
    /// <summary>
    /// 退貨明細編號
    /// </summary>
    public int RmaItemId { get; set; }

    /// <summary>
    /// 申請單編號（FK）
    /// </summary>
    public int RetuenRequestId { get; set; }

    /// <summary>
    /// 訂單編號（FK）
    /// </summary>
    public int OrderId { get; set; }

    /// <summary>
    /// 原訂單明細編號（FK）；與 RetuenRequestId 組合唯一
    /// </summary>
    public int OrderItemId { get; set; }

    /// <summary>
    /// 申請數量；CHECK：&gt;= 1
    /// </summary>
    public int Qty { get; set; }

    /// <summary>
    /// 核准數量；CHECK：&gt;= 0
    /// </summary>
    public int ApprovedQty { get; set; }

    /// <summary>
    /// 退款數量（僅 refund+items 使用；0~ApprovedQty）
    /// </summary>
    public int RefundQty { get; set; }

    /// <summary>
    /// 補寄數量（僅 reship 使用；0~ApprovedQty）
    /// </summary>
    public int ReshipQty { get; set; }

    /// <summary>
    /// 退款單價
    /// </summary>
    public decimal? RefundUnitAmount { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual OrdOrder Order { get; set; }

    public virtual OrdOrderItem OrderItem { get; set; }

    public virtual OrdReturnRequest RetuenRequest { get; set; }
}