// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 商品屬性明細表，可同時設定多種屬性
/// </summary>
public partial class ProdProductAttribute
{
    /// <summary>
    /// 商品ID（外鍵）
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// 屬性ID（外鍵）
    /// </summary>
    public int AttributeId { get; set; }

    /// <summary>
    /// 屬性選項ID
    /// </summary>
    public int AttributeOptionId { get; set; }

    /// <summary>
    /// 屬性值
    /// </summary>
    public string AttributeValue { get; set; }

    public virtual ProdAttribute Attribute { get; set; }

    public virtual ProdAttributeOption AttributeOption { get; set; }

    public virtual ProdProduct Product { get; set; }
}