// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 商品問答的回答端；可標示官方回覆
/// </summary>
public partial class ProdProductAnswer
{
    /// <summary>
    /// 回答ID（主鍵）
    /// </summary>
    public int AnswerId { get; set; }

    /// <summary>
    /// 問題ID（外鍵）
    /// </summary>
    public int QuestionId { get; set; }

    /// <summary>
    /// 回答者會員ID（可為商家/客服/一般會員）
    /// </summary>
    public int UserNumberId { get; set; }

    /// <summary>
    /// 回答內容
    /// </summary>
    public string AnswerContent { get; set; }

    /// <summary>
    /// 回答時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 是否官方回覆（商家/客服）
    /// </summary>
    public bool IsOfficial { get; set; }

    /// <summary>
    /// 是否通過審核
    /// </summary>
    public bool IsApproved { get; set; }

    public virtual ProdProductQuestion Question { get; set; }
}