// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 商品的分類明細表，一個商品可對應多個分類
/// </summary>
public partial class ProdProductType
{
    /// <summary>
    /// 商品ID（外鍵）
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// 分類ID（外鍵）
    /// </summary>
    public int ProductTypeId { get; set; }

    /// <summary>
    /// 是否為主分類（1=是）
    /// </summary>
    public bool IsPrimary { get; set; }

    public virtual ProdProduct Product { get; set; }

    public virtual ProdProductTypeConfig ProductType { get; set; }
}