// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 品牌收藏表
/// </summary>
public partial class SupBrandFavorite
{
    /// <summary>
    /// 關聯會員Id
    /// </summary>
    public int UserNumberId { get; set; }

    /// <summary>
    /// 關聯品牌Id
    /// </summary>
    public int BrandId { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    public virtual SupBrand Brand { get; set; }
}