// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 物流方式
/// </summary>
public partial class SupLogistics
{
    /// <summary>
    /// 主鍵
    /// </summary>
    public int LogisticsId { get; set; }

    public string ShippingMethod { get; set; }

    /// <summary>
    /// 物流商名稱
    /// </summary>
    public string LogisticsName { get; set; }

    /// <summary>
    /// 是否啟用
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// 建檔人員
    /// </summary>
    public int? Creator { get; set; }

    /// <summary>
    /// 建檔時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動人員
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual ICollection<OrdOrder> OrdOrder { get; set; } = new List<OrdOrder>();

    public virtual ICollection<OrdShipping> OrdShipping { get; set; } = new List<OrdShipping>();

    public virtual ICollection<SupLogisticsRate> SupLogisticsRate { get; set; } = new List<SupLogisticsRate>();
}