// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 管理員登入紀錄
/// </summary>
public partial class UserLoginLog
{
    /// <summary>
    /// 登入紀錄 ID
    /// </summary>
    public int LoginLogId { get; set; }

    /// <summary>
    /// 登入者 ID
    /// </summary>
    public int AdminId { get; set; }

    /// <summary>
    /// 登入時間
    /// </summary>
    public DateTime LoginDate { get; set; }

    /// <summary>
    /// 登出時間
    /// </summary>
    public DateTime? LogoutDate { get; set; }

    /// <summary>
    /// 登入 IP
    /// </summary>
    public string LoginIp { get; set; }

    /// <summary>
    /// 登入結果
    /// </summary>
    public string LoginResult { get; set; }
}