// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 後台管理員與角色關聯
/// </summary>
public partial class UserAdminRole
{
    /// <summary>
    /// 管理員角色 ID
    /// </summary>
    public int AdminRoleId { get; set; }

    /// <summary>
    /// 角色名稱
    /// </summary>
    public string RoleName { get; set; }

    /// <summary>
    /// 建立時間 (UTC)
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 建立人員 ID
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 異動人員 ID
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual ICollection<UserRoleModule> UserRoleModule { get; set; } = new List<UserRoleModule>();
}