// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 會員付款方式
/// </summary>
public partial class UserMemberPaymentMethod
{
    /// <summary>
    /// 付款方式 ID
    /// </summary>
    public int PaymentMethodId { get; set; }

    /// <summary>
    /// 會員 ID
    /// </summary>
    public int UserNumberId { get; set; }

    /// <summary>
    /// 金流服務商代碼
    /// </summary>
    public string PaymentGatewayCode { get; set; }

    /// <summary>
    /// 付款方式類型
    /// </summary>
    public string PaymentMethodType { get; set; }

    /// <summary>
    /// 代號化付款憑證
    /// </summary>
    public string PaymentToken { get; set; }

    /// <summary>
    /// 是否為預設付款方式
    /// </summary>
    public bool IsDefault { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 修改時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    /// <summary>
    /// 備註說明
    /// </summary>
    public string Note { get; set; }

    public virtual ICollection<UserCreditCardInfo> UserCreditCardInfo { get; set; } = new List<UserCreditCardInfo>();
}