// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Core.DTOs.SUP;

/// <summary>
/// 庫存批次
/// </summary>
public partial class SupStockBatchDto
{
	public int StockBatchId { get; set; }
	public int SkuId { get; set; }
	public string? SkuCode { get; set; }
	public string? ProductName { get; set; }
	public string? BrandName { get; set; }
	public string? BatchNumber { get; set; }
	public bool IsSellable { get; set; }
	public DateTime? ManufactureDate { get; set; }
	public DateTime? ExpireDate { get; set; }
	public int Qty { get; set; }
	public int SafetyStockQty { get; set; }
	public int ReorderPoint { get; set; }
	public int MaxStockQty { get; set; }
	public int? Creator { get; set; }
	public DateTime CreatedDate { get; set; }
	public int? Reviser { get; set; }
	public DateTime? RevisedDate { get; set; }


}