// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Core.DTOs;

/// <summary>
/// 通用媒體庫（圖片/影片/檔案）
/// </summary>
public partial class SysAssetFileDto
{
    /// <summary>
    /// 主鍵 ID
    /// </summary>
    public int FileId { get; set; }

    /// <summary>
    /// 雜湊或GUID，用來防重複
    /// </summary>
    public string FileKey { get; set; }

    /// <summary>
    /// 是否外部URL
    /// </summary>
    public bool IsExternal { get; set; }

    /// <summary>
    /// 完整URL或相對路徑
    /// </summary>
    public string FileUrl { get; set; }

    /// <summary>
    /// 副檔名，例如 jpg, png, webp
    /// </summary>
    public string FileExt { get; set; }

    /// <summary>
    /// image/jpeg, image/png, video/mp4
    /// </summary>
    public string MimeType { get; set; }

    /// <summary>
    /// 影像寬度（非影像類型可為 NULL）
    /// </summary>
    public int? Width { get; set; }

    /// <summary>
    /// 影像高度（非影像類型可為 NULL）
    /// </summary>
    public int? Height { get; set; }

    /// <summary>
    /// 檔案大小（byte 為單位）
    /// </summary>
    public long? FileSizeBytes { get; set; }

    /// <summary>
    /// Alt 替代文字
    /// </summary>
    public string AltText { get; set; }

    /// <summary>
    /// 文字說明 / 附註文字
    /// </summary>
    public string Caption { get; set; }

    /// <summary>
    /// 建檔時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 是否有效
    /// </summary>
    public bool IsActive { get; set; }
}