// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

public partial class AspNetRole
{
    public string Id { get; set; }

    public string Description { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? RevisedDate { get; set; }

    public int Creator { get; set; }

    public int? Reviser { get; set; }

    public string Name { get; set; }

    public string NormalizedName { get; set; }

    public string ConcurrencyStamp { get; set; }

    public virtual ICollection<AspNetRoleClaim> AspNetRoleClaims { get; set; } = new List<AspNetRoleClaim>();

    public virtual ICollection<UserRoleModule> UserRoleModules { get; set; } = new List<UserRoleModule>();

    public virtual ICollection<AspNetUser> Users { get; set; } = new List<AspNetUser>();
}