// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 資料類別主檔（樣品基本資料、加工程度等）
/// </summary>
public partial class CntDataType
{
    /// <summary>
    /// 資料類別 ID
    /// </summary>
    public int DataTypeId { get; set; }

    /// <summary>
    /// 資料類別名稱
    /// </summary>
    public string TypeName { get; set; }

    public virtual ICollection<CntSample> CntSamples { get; set; } = new List<CntSample>();
}