// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 食品分類主檔
/// </summary>
public partial class CntFoodCategory
{
    /// <summary>
    /// 食品分類 ID
    /// </summary>
    public int CategoryId { get; set; }

    /// <summary>
    /// 食品分類名稱
    /// </summary>
    public string CategoryName { get; set; }

    public virtual ICollection<CntSample> CntSamples { get; set; } = new List<CntSample>();
}