// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 媒體資源
/// </summary>
public partial class CntMedium
{
    /// <summary>
    /// 媒體 ID
    /// </summary>
    public int MediaId { get; set; }

    /// <summary>
    /// 對應區塊 ID
    /// </summary>
    public int PageBlockId { get; set; }

    /// <summary>
    /// 檔案 ID
    /// </summary>
    public int? FileId { get; set; }

    /// <summary>
    /// 上傳時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    public virtual SysAssetFile File { get; set; }

    public virtual CntPageBlock PageBlock { get; set; }
}