// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 營養成分暫存表（原始資料匯入暫存用）
/// </summary>
public partial class CntNutritionStaging
{
    /// <summary>
    /// 暫存資料 ID
    /// </summary>
    public int NutritionStagingId { get; set; }

    /// <summary>
    /// 食品分類
    /// </summary>
    public string FoodCategory { get; set; }

    /// <summary>
    /// 資料類別
    /// </summary>
    public string DataType { get; set; }

    /// <summary>
    /// 整合代碼（原始資料代號）
    /// </summary>
    public string IntegrationCode { get; set; }

    /// <summary>
    /// 樣本名稱
    /// </summary>
    public string SampleName { get; set; }

    /// <summary>
    /// 樣本別名
    /// </summary>
    public string AliasName { get; set; }

    /// <summary>
    /// 樣本英文名稱
    /// </summary>
    public string SampleNameEn { get; set; }

    /// <summary>
    /// 內容描述
    /// </summary>
    public string ContentDesc { get; set; }

    /// <summary>
    /// 廢棄率（%）
    /// </summary>
    public decimal? WasteRate { get; set; }

    /// <summary>
    /// 成分類別
    /// </summary>
    public string AnalyteCategory { get; set; }

    /// <summary>
    /// 成分名稱
    /// </summary>
    public string AnalyteName { get; set; }

    /// <summary>
    /// 單位
    /// </summary>
    public string Unit { get; set; }

    /// <summary>
    /// 每100g含量
    /// </summary>
    public string Per100g { get; set; }

    /// <summary>
    /// 樣本數
    /// </summary>
    public int? SampleSizeN { get; set; }

    /// <summary>
    /// 標準差
    /// </summary>
    public decimal? StdDev { get; set; }

    /// <summary>
    /// 每單位含量
    /// </summary>
    public decimal? PerUnitAmount { get; set; }

    /// <summary>
    /// 單位重量（文字）
    /// </summary>
    public string UnitWeightText { get; set; }

    /// <summary>
    /// 單位重量數值
    /// </summary>
    public decimal? UnitWeightContent { get; set; }

    /// <summary>
    /// 建檔人員
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 建立時間 (UTC)
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動人員
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }
}