// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 營養成分主表
/// </summary>
public partial class CntNutritionFact
{
    /// <summary>
    /// 主鍵 ID
    /// </summary>
    public long NutritionFactId { get; set; }

    /// <summary>
    /// 食品分類
    /// </summary>
    public string FoodCategory { get; set; }

    /// <summary>
    /// 資料類別
    /// </summary>
    public string DataType { get; set; }

    /// <summary>
    /// 整合編號
    /// </summary>
    public string IntegrationCode { get; set; }

    /// <summary>
    /// 樣品名稱
    /// </summary>
    public string SampleName { get; set; }

    /// <summary>
    /// 俗名
    /// </summary>
    public string AliasName { get; set; }

    /// <summary>
    /// 樣品英文名稱
    /// </summary>
    public string SampleNameEn { get; set; }

    /// <summary>
    /// 內容物描述
    /// </summary>
    public string ContentDesc { get; set; }

    /// <summary>
    /// 廢棄率（%）
    /// </summary>
    public decimal? WasteRate { get; set; }

    /// <summary>
    /// 分析項分類
    /// </summary>
    public string AnalyteCategory { get; set; }

    /// <summary>
    /// 分析項
    /// </summary>
    public string AnalyteName { get; set; }

    /// <summary>
    /// 含量單位
    /// </summary>
    public string Unit { get; set; }

    /// <summary>
    /// 每100克含量
    /// </summary>
    public string Per100g { get; set; }

    /// <summary>
    /// 樣本數
    /// </summary>
    public int? SampleSizeN { get; set; }

    /// <summary>
    /// 標準差
    /// </summary>
    public decimal? StdDev { get; set; }

    /// <summary>
    /// 每單位含量
    /// </summary>
    public decimal? PerUnitAmount { get; set; }

    /// <summary>
    /// 每單位重（文字）
    /// </summary>
    public string UnitWeightText { get; set; }

    /// <summary>
    /// 每單位重（數值）
    /// </summary>
    public decimal? UnitWeightValue { get; set; }

    /// <summary>
    /// 每單位重含量
    /// </summary>
    public decimal? UnitWeightContent { get; set; }

    /// <summary>
    /// 建檔人員
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動人員
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }
}