// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 商品與標籤關聯表
/// </summary>
public partial class CntProductTag
{
    /// <summary>
    /// 關聯記錄ID
    /// </summary>
    public long ProductTagId { get; set; }

    /// <summary>
    /// 商品ID
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// 標籤ID
    /// </summary>
    public int TagId { get; set; }

    /// <summary>
    /// 是否前台顯示
    /// </summary>
    public bool IsVisible { get; set; }

    /// <summary>
    /// 是否主要標籤
    /// </summary>
    public bool IsPrimary { get; set; }

    /// <summary>
    /// 顯示順序
    /// </summary>
    public int DisplayOrder { get; set; }

    /// <summary>
    /// 軟刪除旗標
    /// </summary>
    public bool IsDeleted { get; set; }

    /// <summary>
    /// 建檔人員
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動人員
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual ProdProduct Product { get; set; }

    public virtual CntTag Tag { get; set; }
}