// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 頁面與標籤關聯表
/// </summary>
public partial class CntPageTag
{
    /// <summary>
    /// 頁面 ID
    /// </summary>
    public int PageId { get; set; }

    /// <summary>
    /// 標籤 ID
    /// </summary>
    public int TagId { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    public virtual CntPage Page { get; set; }

    public virtual CntTag Tag { get; set; }
}