// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 樣品主檔（對應營養成分樣本資料）
/// </summary>
public partial class CntSample
{
    /// <summary>
    /// 樣品 ID
    /// </summary>
    public int SampleId { get; set; }

    /// <summary>
    /// 整合編號（唯一）
    /// </summary>
    public string IntegrationCode { get; set; }

    /// <summary>
    /// 食品分類 ID
    /// </summary>
    public int CategoryId { get; set; }

    /// <summary>
    /// 資料類別 ID
    /// </summary>
    public int DataTypeId { get; set; }

    /// <summary>
    /// 樣品名稱
    /// </summary>
    public string SampleName { get; set; }

    /// <summary>
    /// 俗名
    /// </summary>
    public string AliasName { get; set; }

    /// <summary>
    /// 樣品英文名稱
    /// </summary>
    public string SampleNameEn { get; set; }

    /// <summary>
    /// 內容物描述
    /// </summary>
    public string ContentDesc { get; set; }

    /// <summary>
    /// 廢棄率（%）
    /// </summary>
    public decimal? WasteRate { get; set; }

    /// <summary>
    /// 建檔人員
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 建立時間 (UTC)
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動人員
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual CntFoodCategory Category { get; set; }

    public virtual ICollection<CntMeasurement> CntMeasurements { get; set; } = new List<CntMeasurement>();

    public virtual CntDataType DataType { get; set; }
}