// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 頁面排程
/// </summary>
public partial class CntSchedule
{
    /// <summary>
    /// 排程 ID
    /// </summary>
    public int ScheduleId { get; set; }

    /// <summary>
    /// 頁面 ID
    /// </summary>
    public int PageId { get; set; }

    /// <summary>
    /// 排程動作
    /// </summary>
    public string ActionType { get; set; }

    /// <summary>
    /// 排程時間
    /// </summary>
    public DateTime ScheduledDate { get; set; }

    /// <summary>
    /// 排程狀態
    /// </summary>
    public string Status { get; set; }

    public virtual CntPage Page { get; set; }
}