// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 標籤
/// </summary>
public partial class CntTag
{
    /// <summary>
    /// 標籤 ID
    /// </summary>
    public int TagId { get; set; }

    /// <summary>
    /// 標籤名稱
    /// </summary>
    public string TagName { get; set; }

    /// <summary>
    /// 是否啟用（0=否，1=是）
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// 異動人員
    /// </summary>
    public string Revisor { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual ICollection<CntPageTag> CntPageTags { get; set; } = new List<CntPageTag>();
}