// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 前台聊天式自助客服—會話
/// </summary>
public partial class CsChatSession
{
    /// <summary>
    /// 會話主鍵
    /// </summary>
    public int SessionId { get; set; }

    /// <summary>
    /// 會員ID（可空）
    /// </summary>
    public int? UserId { get; set; }

    /// <summary>
    /// 1=Web
    /// </summary>
    public int Channel { get; set; }

    /// <summary>
    /// 1=機器人、2=已轉人工、3=已關閉
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// 最近推送的 FAQ（可空）
    /// </summary>
    public int? LastFaqId { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual ICollection<CsChatMessage> CsChatMessages { get; set; } = new List<CsChatMessage>();

    public virtual CsFaq LastFaq { get; set; }
}