// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 前台聊天式自助客服—訊息
/// </summary>
public partial class CsChatMessage
{
    /// <summary>
    /// 主鍵
    /// </summary>
    public int MessageId { get; set; }

    /// <summary>
    /// 所屬會話
    /// </summary>
    public int SessionId { get; set; }

    /// <summary>
    /// 0=使用者、1=機器人、2=客服
    /// </summary>
    public int SenderType { get; set; }

    /// <summary>
    /// 訊息內容
    /// </summary>
    public string Message { get; set; }

    /// <summary>
    /// 若回覆為 FAQ（可空）
    /// </summary>
    public int? FaqId { get; set; }

    /// <summary>
    /// 套用的規則（可空）
    /// </summary>
    public int? RuleId { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    public virtual CsFaq Faq { get; set; }

    public virtual CsAutoReplyRule Rule { get; set; }

    public virtual CsChatSession Session { get; set; }
}