// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// FAQ 成效回饋
/// </summary>
public partial class CsFaqFeedback
{
    /// <summary>
    /// 主鍵
    /// </summary>
    public int FeedbackId { get; set; }

    /// <summary>
    /// 對應 FAQ
    /// </summary>
    public int FaqId { get; set; }

    /// <summary>
    /// 是否有幫助（??=true／??=false）
    /// </summary>
    public bool IsHelpful { get; set; }

    /// <summary>
    /// 會員ID（訪客可空）
    /// </summary>
    public int? UserId { get; set; }

    /// <summary>
    /// 前台 Session 追蹤
    /// </summary>
    public string ClientSessionKey { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    public virtual CsFaq Faq { get; set; }
}