// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// FAQ 分類
/// </summary>
public partial class CsFaqCategory
{
    /// <summary>
    /// 分類主鍵
    /// </summary>
    public int CategoryId { get; set; }

    /// <summary>
    /// 上層分類（可空，多層）
    /// </summary>
    public int? ParentCategoryId { get; set; }

    /// <summary>
    /// 分類名稱
    /// </summary>
    public string CategoryName { get; set; }

    /// <summary>
    /// 排序（小在前）
    /// </summary>
    public int OrderSeq { get; set; }

    /// <summary>
    /// 是否啟用
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// 建檔時間(UTC)
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動時間(UTC)
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual ICollection<CsFaq> CsFaqs { get; set; } = new List<CsFaq>();

    public virtual ICollection<CsTicket> CsTickets { get; set; } = new List<CsTicket>();

    public virtual ICollection<CsFaqCategory> InverseParentCategory { get; set; } = new List<CsFaqCategory>();

    public virtual CsFaqCategory ParentCategory { get; set; }
}