// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 客服工單訊息
/// </summary>
public partial class CsTicketMessage
{
    /// <summary>
    /// 訊息 ID
    /// </summary>
    public int MessageId { get; set; }

    /// <summary>
    /// 所屬工單 ID
    /// </summary>
    public int TicketId { get; set; }

    /// <summary>
    /// 發送者類型（1=客戶，2=客服）
    /// </summary>
    public byte SenderType { get; set; }

    /// <summary>
    /// 訊息內容
    /// </summary>
    public string MessageText { get; set; }

    /// <summary>
    /// 附件路徑（可空）
    /// </summary>
    public string AttachmentUrl { get; set; }

    /// <summary>
    /// 建立時間 (UTC)
    /// </summary>
    public DateTime CreatedDate { get; set; }

    public virtual CsTicket Ticket { get; set; }
}