// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 客服工單歷程
/// </summary>
public partial class CsTicketHistory
{
    /// <summary>
    /// 歷程 ID
    /// </summary>
    public int HistoryId { get; set; }

    /// <summary>
    /// 對應工單 ID
    /// </summary>
    public int TicketId { get; set; }

    /// <summary>
    /// 動作名稱（建立 / 回覆 / 轉單 / 結案）
    /// </summary>
    public string Action { get; set; }

    /// <summary>
    /// 原負責客服
    /// </summary>
    public int? FromAssigneeId { get; set; }

    /// <summary>
    /// 新負責客服
    /// </summary>
    public int? ToAssigneeId { get; set; }

    /// <summary>
    /// 原狀態
    /// </summary>
    public byte? OldStatus { get; set; }

    /// <summary>
    /// 新狀態
    /// </summary>
    public byte? NewStatus { get; set; }

    /// <summary>
    /// 備註說明
    /// </summary>
    public string Note { get; set; }

    /// <summary>
    /// 操作者 ID
    /// </summary>
    public int ChangedBy { get; set; }

    /// <summary>
    /// 異動時間 (UTC)
    /// </summary>
    public DateTime ChangedDate { get; set; }

    public virtual CsTicket Ticket { get; set; }
}