// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 廣告與位置對應表
/// </summary>
public partial class MktAdPlacementMap
{
    /// <summary>
    /// 對應編號
    /// </summary>
    public int MapId { get; set; }

    /// <summary>
    /// 廣告編號
    /// </summary>
    public int AdId { get; set; }

    /// <summary>
    /// 位置編號
    /// </summary>
    public int PlacementId { get; set; }

    public virtual MktAd Ad { get; set; }

    public virtual MktPlacement Placement { get; set; }
}