// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 活動遊戲紀錄
/// </summary>
public partial class MktGameRecord
{
    /// <summary>
    /// 主鍵，自動遞增 ID
    /// </summary>
    public int GameRecordId { get; set; }

    /// <summary>
    /// 會員 ID (FK)
    /// </summary>
    public int UserNumberId { get; set; }

    /// <summary>
    /// 當局得分
    /// </summary>
    public int Score { get; set; }

    /// <summary>
    /// 兌換金額
    /// </summary>
    public int CouponAmount { get; set; }

    /// <summary>
    /// 遊戲日期（同會員每日僅一筆）
    /// </summary>
    public DateOnly PlayedDate { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }
}