// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 品項層級折扣/調整（多品牌時逐品項計算95折）
/// </summary>
public partial class OrdOrderItemAdjustment
{
    /// <summary>
    /// 調整明細主鍵
    /// </summary>
    public int AdjustmentItemId { get; set; }

    /// <summary>
    /// FK: Order（冗餘方便查詢彙總）
    /// </summary>
    public int OrderId { get; set; }

    /// <summary>
    /// FK: OrderItem
    /// </summary>
    public int OrderItemId { get; set; }

    /// <summary>
    /// 來源：coupon/brand/site/other
    /// </summary>
    public string Kind { get; set; }

    /// <summary>
    /// 計算：percentage/fixed
    /// </summary>
    public string Method { get; set; }

    /// <summary>
    /// 比例；範例：0.95=95折(**串供應商表)
    /// </summary>
    public decimal? DiscountRate { get; set; }

    /// <summary>
    /// 本筆金額（折扣為負值）
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual OrdOrder Order { get; set; }

    public virtual OrdOrderItem OrderItem { get; set; }
}