// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 付款方式明細
/// </summary>
public partial class OrdPayment
{
    /// <summary>
    /// 付款紀錄編號
    /// </summary>
    public int PaymentId { get; set; }

    /// <summary>
    /// 訂單編號（FK）; YYYYMMDD#######
    /// </summary>
    public int OrderId { get; set; }

    /// <summary>
    /// 付款方式（FK）
    /// </summary>
    public int PaymentConfigId { get; set; }

    /// <summary>
    /// 金額(元)
    /// </summary>
    public int Amount { get; set; }

    /// <summary>
    /// 狀態：pending/success/failed/refund
    /// </summary>
    public string Status { get; set; }

    /// <summary>
    /// 第三方交易號；允許NULL；主關聯至 ECPay
    /// </summary>
    public string TradeNo { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 對外交易編號；允許NULL
    /// </summary>
    public string MerchantTradeNo { get; set; }

    /// <summary>
    /// 付款完成時間
    /// </summary>
    public DateTime? TradeDate { get; set; }

    /// <summary>
    /// 模擬付款；1=學術/測試；不入帳/不出貨
    /// </summary>
    public bool SimulatePaid { get; set; }

    /// <summary>
    /// 回傳代碼
    /// </summary>
    public int? RtnCode { get; set; }

    /// <summary>
    /// 回傳訊息
    /// </summary>
    public string RtnMsg { get; set; }

    /// <summary>
    /// 驗簽原文
    /// </summary>
    public string CheckMacValue { get; set; }

    /// <summary>
    /// 退款型交易才填；一般授權/請款為 NULL（FK→ORD_ReturnRequest）
    /// </summary>
    public int? ReturnRequestId { get; set; }

    public virtual OrdOrder Order { get; set; }

    public virtual OrdPaymentConfig PaymentConfig { get; set; }

    public virtual OrdReturnRequest ReturnRequest { get; set; }
}