// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 退貨申請 refund + order：整筆退款（不建明細）；refund + items：部分退款（需建明細）；reship：缺件補寄（需建明細；不換貨）。
/// </summary>
public partial class OrdReturnRequest
{
    /// <summary>
    /// 申請單編號
    /// </summary>
    public int ReturnRequestId { get; set; }

    public string RmaId { get; set; }

    /// <summary>
    /// 訂單編號（FK）
    /// </summary>
    public int OrderId { get; set; }

    /// <summary>
    /// 申請類型：refund/reship（建議CHECK）
    /// </summary>
    public string RequestType { get; set; }

    /// <summary>
    /// 退款範圍：order=整筆 / items=品項（僅在 refund 時有用）
    /// </summary>
    public string RefundScope { get; set; }

    /// <summary>
    /// 原因代碼：damaged/missing/wrong/quality...
    /// </summary>
    public string ReasonCode { get; set; }

    /// <summary>
    /// 原因描述
    /// </summary>
    public string ReasonText { get; set; }

    /// <summary>
    /// 附件網址
    /// </summary>
    public int? AttachmentUrlId { get; set; }

    /// <summary>
    /// 流程：pending/review/refunding/done/rejected（建議CHECK）
    /// </summary>
    public string Status { get; set; }

    /// <summary>
    /// 建檔人員(**串會員資料)
    /// </summary>
    public int? Creator { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動時間（；更新時改寫）
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    /// <summary>
    /// 審核者（預留 AdminUsers，**串權限資料）
    /// </summary>
    public int? Reviewer { get; set; }

    /// <summary>
    /// 審核時間
    /// </summary>
    public DateTime? ReviewedDate { get; set; }

    /// <summary>
    /// 審核意見
    /// </summary>
    public string ReviewComment { get; set; }

    public virtual SysAssetFile AttachmentUrl { get; set; }

    public virtual ICollection<OrdPayment> OrdPayments { get; set; } = new List<OrdPayment>();

    public virtual ICollection<OrdReturnItem> OrdReturnItems { get; set; } = new List<OrdReturnItem>();

    public virtual OrdOrder Order { get; set; }
}