// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 商品問答的問題端；可搭配審核流程
/// </summary>
public partial class ProdProductQuestion
{
    /// <summary>
    /// 問題ID（主鍵）
    /// </summary>
    public int QuestionId { get; set; }

    /// <summary>
    /// 商品ID（外鍵）
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// 提問會員ID（外鍵）
    /// </summary>
    public int UserNumberId { get; set; }

    /// <summary>
    /// 問題內容
    /// </summary>
    public string QuestionContent { get; set; }

    /// <summary>
    /// 提問時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 是否通過審核（可做敏感詞過濾）
    /// </summary>
    public bool IsApproved { get; set; }

    public virtual ICollection<ProdProductAnswer> ProdProductAnswers { get; set; } = new List<ProdProductAnswer>();

    public virtual ProdProduct Product { get; set; }
}