// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// SKU層級與即時庫存(支援多規格)
/// </summary>
public partial class ProdProductSku
{
    /// <summary>
    /// SKU ID（主鍵）
    /// </summary>
    public int SkuId { get; set; }

    /// <summary>
    /// 規格碼
    /// </summary>
    public string SpecCode { get; set; }

    /// <summary>
    /// SKU代碼
    /// </summary>
    public string SkuCode { get; set; }

    /// <summary>
    /// 商品ID（外鍵）
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// 條碼
    /// </summary>
    public string Barcode { get; set; }

    /// <summary>
    /// 成本價
    /// </summary>
    public decimal? CostPrice { get; set; }

    /// <summary>
    /// 原價
    /// </summary>
    public decimal? ListPrice { get; set; }

    /// <summary>
    /// 單價
    /// </summary>
    public decimal? UnitPrice { get; set; }

    /// <summary>
    /// 優惠價
    /// </summary>
    public decimal? SalePrice { get; set; }

    /// <summary>
    /// 目前庫存
    /// </summary>
    public int StockQty { get; set; }

    /// <summary>
    /// 安全庫存量（低於提醒）
    /// </summary>
    public int SafetyStockQty { get; set; }

    /// <summary>
    /// 再訂購點（≧安全庫存量）
    /// </summary>
    public int ReorderPoint { get; set; }

    /// <summary>
    /// 最大庫存量（0=不限制)
    /// </summary>
    public int MaxStockQty { get; set; }

    /// <summary>
    /// 是否允許缺貨預購（1=可超賣，0=禁止）
    /// </summary>
    public bool IsAllowBackorder { get; set; }

    /// <summary>
    /// 有效天數
    /// </summary>
    public int ShelfLifeDays { get; set; }

    /// <summary>
    /// 上架開始時間
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>
    /// 下架時間（NULL=無限期）
    /// </summary>
    public DateTime? EndDate { get; set; }

    /// <summary>
    /// 是否啟用
    /// </summary>
    public bool IsActive { get; set; }

    public virtual ICollection<OrdOrderItem> OrdOrderItems { get; set; } = new List<OrdOrderItem>();

    public virtual ICollection<OrdShoppingCartItem> OrdShoppingCartItems { get; set; } = new List<OrdShoppingCartItem>();

    public virtual ICollection<ProdProductImage> ProdProductImages { get; set; } = new List<ProdProductImage>();

    public virtual ICollection<ProdProductReview> ProdProductReviews { get; set; } = new List<ProdProductReview>();

    public virtual ProdProduct Product { get; set; }

    public virtual ICollection<SupStockBatch> SupStockBatches { get; set; } = new List<SupStockBatch>();

    public virtual ICollection<ProdSpecificationOption> SpecificationOptions { get; set; } = new List<ProdSpecificationOption>();
}