// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 商品屬性定義，可用於篩選與分類，例如功效、性別、年齡層等
/// </summary>
public partial class ProdAttribute
{
    /// <summary>
    /// 屬性ID（主鍵）
    /// </summary>
    public int AttributeId { get; set; }

    /// <summary>
    /// 屬性名稱（例如：功效、性別、年齡）
    /// </summary>
    public string AttributeName { get; set; }

    /// <summary>
    /// 屬性資料型別（text/number/check/select）
    /// </summary>
    public string DataType { get; set; }

    public virtual ICollection<ProdAttributeOption> ProdAttributeOptions { get; set; } = new List<ProdAttributeOption>();

    public virtual ICollection<ProdProductAttribute> ProdProductAttributes { get; set; } = new List<ProdProductAttribute>();
}