// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 商品成分明細；一個商品可對應多個成分
/// </summary>
public partial class ProdProductIngredient
{
    /// <summary>
    /// 商品ID（外鍵）
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// 成分ID（外鍵）
    /// </summary>
    public int IngredientId { get; set; }

    /// <summary>
    /// 百分比或含量（單位可於前台說明）
    /// </summary>
    public decimal? Percentage { get; set; }

    /// <summary>
    /// 劑量、產地或其他備註
    /// </summary>
    public string Note { get; set; }

    /// <summary>
    /// 成分類型：1=主成分、2=其他成分、3=過敏原、4=製程附註
    /// </summary>
    public byte IngredientType { get; set; }

    /// <summary>
    /// 顯示順序
    /// </summary>
    public int OrderSeq { get; set; }

    public virtual ProdIngredient Ingredient { get; set; }

    public virtual ProdProduct Product { get; set; }
}