// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 套組明細表：記錄套組內有哪些子商品
/// </summary>
public partial class ProdBundleItem
{
    /// <summary>
    /// 套組ID (FK)
    /// </summary>
    public int BundleId { get; set; }

    /// <summary>
    /// 商品ID (FK)
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime? CreatedDate { get; set; }

    public virtual ProdBundle Bundle { get; set; }

    public virtual ProdProduct Product { get; set; }
}