// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

public partial class RefreshToken
{
    public long Id { get; set; }

    public string UserId { get; set; }

    public string TokenHash { get; set; }

    public DateTime ExpiresAtUtc { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? RevokedAtUtc { get; set; }

    public long? ReplacedByTokenId { get; set; }

    public string JwtId { get; set; }

    public virtual AspNetUser User { get; set; }
}