// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 品牌與商品分類關聯表，用於設定品牌專頁篩選按鈕顯示內容
/// </summary>
public partial class SupBrandProductTypeFilter
{
    /// <summary>
    /// 關聯記錄ID
    /// </summary>
    public int BrandProductTypeFilterId { get; set; }

    /// <summary>
    /// 品牌ID (FK)
    /// </summary>
    public int BrandId { get; set; }

    /// <summary>
    /// 商品分類ID (FK)
    /// </summary>
    public int ProductTypeId { get; set; }

    /// <summary>
    /// 按鈕顯示文字（如運動補充劑）
    /// </summary>
    public string ButtonText { get; set; }

    /// <summary>
    /// 按鈕顯示順序（數字越小越前面）
    /// </summary>
    public int ButtonOrder { get; set; }

    /// <summary>
    /// 是否啟用（1=啟用, 0=停用）
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// 建立時間 (UTC)
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 建檔人員
    /// </summary>
    public int? Creator { get; set; }

    /// <summary>
    /// 異動時間 (UTC)
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    /// <summary>
    /// 異動人員
    /// </summary>
    public int? Reviser { get; set; }

    public virtual SupBrand Brand { get; set; }

    public virtual ProdProductTypeConfig ProductType { get; set; }
}