// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 供應商物流資料
/// </summary>
public partial class SupOrderLogistic
{
    /// <summary>
    /// 物流紀錄 ID
    /// </summary>
    public int OrderLogisticsId { get; set; }

    /// <summary>
    /// 訂單 ID (對應 ORD_Order)
    /// </summary>
    public int OrderId { get; set; }

    /// <summary>
    /// 配送方式：HOME / CVS
    /// </summary>
    public string DeliveryMethod { get; set; }

    /// <summary>
    /// 綠界子類型 (UNIMARTC2C, TCAT...)
    /// </summary>
    public string LogisticsSubType { get; set; }

    /// <summary>
    /// 超商門市代號
    /// </summary>
    public string CvsstoreId { get; set; }

    /// <summary>
    /// 超商門市名稱
    /// </summary>
    public string CvsstoreName { get; set; }

    /// <summary>
    /// 超商門市地址
    /// </summary>
    public string Cvsaddress { get; set; }

    /// <summary>
    /// 綠界物流交易編號
    /// </summary>
    public string AllPayLogisticsId { get; set; }

    /// <summary>
    /// 建立者 ID
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 建立時間 (UTC)
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動人員 ID
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間 (UTC)
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual OrdOrder Order { get; set; }
}