// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 資料夾管理
/// </summary>
public partial class SysFolder
{
    /// <summary>
    /// 資料夾 ID
    /// </summary>
    public int FolderId { get; set; }

    /// <summary>
    /// 資料夾名稱
    /// </summary>
    public string FolderName { get; set; }

    /// <summary>
    /// 上層資料夾 ID（自關聯）
    /// </summary>
    public int? ParentId { get; set; }

    /// <summary>
    /// 是否啟用（1=啟用，0=停用）
    /// </summary>
    public bool IsActive { get; set; }

    public virtual ICollection<SysFolder> InverseParent { get; set; } = new List<SysFolder>();

    public virtual SysFolder Parent { get; set; }
}