// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// SEO 頁面用到的資產（可多張）
/// </summary>
public partial class SysSeoMetaAsset
{
    /// <summary>
    /// 來源 SEO Id
    /// </summary>
    public int SeoId { get; set; }

    /// <summary>
    /// 資產檔案 Id
    /// </summary>
    public int FileId { get; set; }

    /// <summary>
    /// 圖片角色（hero/gallery/og/twitter）
    /// </summary>
    public string Role { get; set; }

    /// <summary>
    /// 顯示順序
    /// </summary>
    public int OrderSeq { get; set; }

    /// <summary>
    /// 主要代表圖（OpenGraph/縮圖優先）
    /// </summary>
    public bool IsPrimary { get; set; }

    /// <summary>
    /// 焦點X%（0~100）
    /// </summary>
    public decimal? FocalX { get; set; }

    /// <summary>
    /// 焦點Y%（0~100）
    /// </summary>
    public decimal? FocalY { get; set; }

    /// <summary>
    /// 圖片在此頁面的替代文字（與檔案本體解耦）
    /// </summary>
    public string AltText { get; set; }

    /// <summary>
    /// 此頁面下的圖片說明文字/附註
    /// </summary>
    public string Caption { get; set; }

    /// <summary>
    /// 註冊時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 上次修改時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    /// <summary>
    /// 是否啟用
    /// </summary>
    public bool IsActive { get; set; }

    public virtual SysAssetFile File { get; set; }

    public virtual SysSeoMetum Seo { get; set; }
}