// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// google tag manager 追蹤碼管理員設定
/// </summary>
public partial class UserGtmManager
{
    /// <summary>
    /// GTM 管理員 ID
    /// </summary>
    public int GtmManagerId { get; set; }

    /// <summary>
    /// GTM 專案 ID
    /// </summary>
    public string GtmId { get; set; }

    /// <summary>
    /// 是否啟用
    /// </summary>
    public bool IsActive { get; set; }
}