// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tHerdBackend.Infra.Models;

/// <summary>
/// 會員通知發送紀錄
/// </summary>
public partial class UserNotificationHistory
{
    /// <summary>
    /// 通知紀錄 ID
    /// </summary>
    public int NotificationHistoryId { get; set; }

    /// <summary>
    /// 會員 ID
    /// </summary>
    public int UserNumberId { get; set; }

    /// <summary>
    /// 通知類型
    /// </summary>
    public string NotificationType { get; set; }

    /// <summary>
    /// 通知標題
    /// </summary>
    public string ContentTitle { get; set; }

    /// <summary>
    /// 通知內容
    /// </summary>
    public string Content { get; set; }

    /// <summary>
    /// 發送管道
    /// </summary>
    public string DeliveryChannel { get; set; }

    /// <summary>
    /// 發送時間
    /// </summary>
    public DateTime SentDate { get; set; }

    /// <summary>
    /// 發送狀態
    /// </summary>
    public string Status { get; set; }

    /// <summary>
    /// 程式來源
    /// </summary>
    public string CodeSource { get; set; }

    /// <summary>
    /// 模組名稱
    /// </summary>
    public string ModuleId { get; set; }

    /// <summary>
    /// 判斷通知是否已讀
    /// </summary>
    public bool IsRead { get; set; }
}