// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// FAQ 主內容
/// </summary>
public partial class CsFaq
{
    /// <summary>
    /// FAQ 主鍵
    /// </summary>
    public int FaqId { get; set; }

    /// <summary>
    /// 問題標題
    /// </summary>
    public string Title { get; set; }

    /// <summary>
    /// 答案內容（可含 HTML）
    /// </summary>
    public string AnswerHtml { get; set; }

    /// <summary>
    /// 0=停用、1=啟用
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// 所屬分類
    /// </summary>
    public int CategoryId { get; set; }

    /// <summary>
    /// 前台顯示排序
    /// </summary>
    public int OrderSeq { get; set; }

    /// <summary>
    /// 最近發布時間（可空）
    /// </summary>
    public DateTime? LastPublishedTime { get; set; }

    /// <summary>
    /// 是否啟用
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// 建檔時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual CsFaqCategory Category { get; set; }

    public virtual ICollection<CsAutoReplyRule> CsAutoReplyRules { get; set; } = new List<CsAutoReplyRule>();

    public virtual ICollection<CsChatMessage> CsChatMessages { get; set; } = new List<CsChatMessage>();

    public virtual ICollection<CsChatSession> CsChatSessions { get; set; } = new List<CsChatSession>();

    public virtual ICollection<CsFaqFeedback> CsFaqFeedbacks { get; set; } = new List<CsFaqFeedback>();

    public virtual ICollection<CsFaqKeyword> CsFaqKeywords { get; set; } = new List<CsFaqKeyword>();
}