// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 評價附圖；一筆一張，便於審核與排序
/// </summary>
public partial class ProdProductReviewImage
{
    /// <summary>
    /// 評價圖片ID（主鍵）
    /// </summary>
    public int ReviewImageId { get; set; }

    /// <summary>
    /// 評價ID（外鍵）
    /// </summary>
    public int ReviewId { get; set; }

    /// <summary>
    /// 圖片檔案ID（外鍵；對應 SYS_AssetFile.FileId）
    /// </summary>
    public int? ImgId { get; set; }

    /// <summary>
    /// 顯示順序（同一評價內排序；預設 0）
    /// </summary>
    public int OrderSeq { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 最後更新時間（異動時更新）
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual SysAssetFile Img { get; set; }

    public virtual ProdProductReview Review { get; set; }
}