// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 商品的規格設定
/// </summary>
public partial class ProdSpecificationConfig
{
    /// <summary>
    /// 規格群組ID（主鍵）
    /// </summary>
    public int SpecificationConfigId { get; set; }

    /// <summary>
    /// 商品ID（外鍵）
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// 規格群組名稱（例如：容量、口味、顏色）
    /// </summary>
    public string GroupName { get; set; }

    /// <summary>
    /// 顯示順序
    /// </summary>
    public int OrderSeq { get; set; }

    public virtual ICollection<ProdSpecificationOption> ProdSpecificationOptions { get; set; } = new List<ProdSpecificationOption>();

    public virtual ProdProduct Product { get; set; }
}