// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 屬性選項
/// </summary>
public partial class ProdAttributeOption
{
    /// <summary>
    /// 屬性選項ID（主鍵）
    /// </summary>
    public int AttributeOptionId { get; set; }

    /// <summary>
    /// 屬性ID（外鍵）
    /// </summary>
    public int AttributeId { get; set; }

    /// <summary>
    /// 選項名稱（如：男性、女性、18-25歲）
    /// </summary>
    public string OptionName { get; set; }

    /// <summary>
    /// 選項值（用於儲存額外代碼或數值）
    /// </summary>
    public string OptionValue { get; set; }

    /// <summary>
    /// 顯示順序
    /// </summary>
    public int OrderSeq { get; set; }

    public virtual ProdAttribute Attribute { get; set; }

    public virtual ICollection<ProdProductAttribute> ProdProductAttributes { get; set; } = new List<ProdProductAttribute>();
}