// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 供應商模組
/// </summary>
public partial class SupSupplier
{
    /// <summary>
    /// 主鍵，自動編號
    /// </summary>
    public int SupplierId { get; set; }

    /// <summary>
    /// 供應商名稱
    /// </summary>
    public string SupplierName { get; set; }

    /// <summary>
    /// 聯絡人
    /// </summary>
    public string ContactName { get; set; }

    /// <summary>
    /// 聯絡電話
    /// </summary>
    public string Phone { get; set; }

    /// <summary>
    /// 電子郵件
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// 是否啟用（0=否，1=是）
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// 建檔人員
    /// </summary>
    public int? Creator { get; set; }

    /// <summary>
    /// 建檔時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動人員
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual ICollection<ProdProduct> ProdProducts { get; set; } = new List<ProdProduct>();

    public virtual ICollection<SupBrand> SupBrands { get; set; } = new List<SupBrand>();
}