// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 營養素分類主檔（維生素、礦物質、脂肪酸等）
/// </summary>
public partial class CntAnalyteCategory
{
    /// <summary>
    /// 營養素分類 ID
    /// </summary>
    public int AnalyteCategoryId { get; set; }

    /// <summary>
    /// 營養素分類名稱
    /// </summary>
    public string CategoryName { get; set; }

    public virtual ICollection<CntAnalyte> CntAnalytes { get; set; } = new List<CntAnalyte>();
}