// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 營養素／分析項主檔
/// </summary>
public partial class CntAnalyte
{
    /// <summary>
    /// 分析項 ID
    /// </summary>
    public int AnalyteId { get; set; }

    /// <summary>
    /// 分析項分類 ID
    /// </summary>
    public int AnalyteCategoryId { get; set; }

    /// <summary>
    /// 分析項名稱
    /// </summary>
    public string AnalyteName { get; set; }

    /// <summary>
    /// 預設單位（mg / ug / kcal）
    /// </summary>
    public string DefaultUnit { get; set; }

    /// <summary>
    /// 是否常用（十大項）
    /// </summary>
    public bool IsPopular { get; set; }

    /// <summary>
    /// 建檔人員
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 建立時間 (UTC)
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動人員
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual CntAnalyteCategory AnalyteCategory { get; set; }

    public virtual ICollection<CntMeasurement> CntMeasurements { get; set; } = new List<CntMeasurement>();
}