// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 樣品 × 營養素觀測值主表
/// </summary>
public partial class CntMeasurement
{
    /// <summary>
    /// 觀測值 ID
    /// </summary>
    public long MeasurementId { get; set; }

    /// <summary>
    /// 樣品 ID（外鍵）
    /// </summary>
    public int SampleId { get; set; }

    /// <summary>
    /// 分析項 ID（外鍵）
    /// </summary>
    public int AnalyteId { get; set; }

    /// <summary>
    /// 實際資料的單位
    /// </summary>
    public string Unit { get; set; }

    /// <summary>
    /// 每100克含量
    /// </summary>
    public decimal? ValuePer100g { get; set; }

    /// <summary>
    /// 樣本數
    /// </summary>
    public int? SampleCount { get; set; }

    /// <summary>
    /// 標準差
    /// </summary>
    public decimal? StdDev { get; set; }

    /// <summary>
    /// 每單位含量
    /// </summary>
    public decimal? ValuePerServing { get; set; }

    /// <summary>
    /// 每單位重（數值）
    /// </summary>
    public decimal? ServingWeightVal { get; set; }

    /// <summary>
    /// 每單位重（原始文字）
    /// </summary>
    public string ServingWeightTxt { get; set; }

    /// <summary>
    /// 特例資訊（JSON 格式）
    /// </summary>
    public string ExtraJson { get; set; }

    /// <summary>
    /// 建檔人員
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 建立時間 (UTC)
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動人員
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual CntAnalyte Analyte { get; set; }

    public virtual CntSample Sample { get; set; }
}