// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 頁面
/// </summary>
public partial class CntPage
{
    /// <summary>
    /// 頁面 ID
    /// </summary>
    public int PageId { get; set; }

    /// <summary>
    /// 分類 ID
    /// </summary>
    public int PageTypeId { get; set; }

    /// <summary>
    /// Seo 設定
    /// </summary>
    public int? SeoId { get; set; }

    /// <summary>
    /// 頁面標題
    /// </summary>
    public string Title { get; set; }

    /// <summary>
    /// 頁面狀態
    /// </summary>
    public string Status { get; set; }

    /// <summary>
    /// 是否為付費內容
    /// </summary>
    public bool IsPaidContent { get; set; }

    /// <summary>
    /// 試閱字元數或行數
    /// </summary>
    public int? PreviewLength { get; set; }

    /// <summary>
    /// 是否在垃圾桶
    /// </summary>
    public bool IsDeleted { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 更新時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    /// <summary>
    /// 發布時間
    /// </summary>
    public DateTime? PublishedDate { get; set; }

    public virtual ICollection<CntPageBlock> CntPageBlocks { get; set; } = new List<CntPageBlock>();

    public virtual ICollection<CntPageTag> CntPageTags { get; set; } = new List<CntPageTag>();

    public virtual ICollection<CntPurchase> CntPurchases { get; set; } = new List<CntPurchase>();

    public virtual ICollection<CntSchedule> CntSchedules { get; set; } = new List<CntSchedule>();

    public virtual ICollection<CntShareClick> CntShareClicks { get; set; } = new List<CntShareClick>();

    public virtual CntPageType PageType { get; set; }

    public virtual SysSeoMetum Seo { get; set; }
}