// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 頁面分類
/// </summary>
public partial class CntPageType
{
    /// <summary>
    /// 分類 ID
    /// </summary>
    public int PageTypeId { get; set; }

    /// <summary>
    /// 分類名稱
    /// </summary>
    public string TypeName { get; set; }

    public virtual ICollection<CntPage> CntPages { get; set; } = new List<CntPage>();
}