// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 工單主表
/// </summary>
public partial class CsTicket
{
    /// <summary>
    /// 工單主鍵
    /// </summary>
    public int TicketId { get; set; }

    /// <summary>
    /// 建單會員（訪客可空）
    /// </summary>
    public int? UserId { get; set; }

    /// <summary>
    /// 問題分類（對齊 FAQ 分類）
    /// </summary>
    public int? CategoryId { get; set; }

    /// <summary>
    /// 工單主旨
    /// </summary>
    public string Subject { get; set; }

    /// <summary>
    /// 0=待處理、1=處理中、2=已完成、3=已關閉
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// 優先序，數字越小越急
    /// </summary>
    public int Priority { get; set; }

    /// <summary>
    /// 建檔時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual CsFaqCategory Category { get; set; }
}