// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 優惠券規則分類檔（定義優惠券類型與條件）
/// </summary>
public partial class MktCouponRule
{
    /// <summary>
    /// 規則Id
    /// </summary>
    public int RuleId { get; set; }

    /// <summary>
    /// 優惠券類型（滿額折扣、免運、折扣百分比）
    /// </summary>
    public string CouponType { get; set; }

    /// <summary>
    /// 預設使用條件（例：滿1000折100、全館免運）
    /// </summary>
    public string DefaultCondition { get; set; }

    /// <summary>
    /// 優惠券說明
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// 是否啟用
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// 建檔人員
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 建檔時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    public virtual ICollection<MktCoupon> MktCoupons { get; set; } = new List<MktCoupon>();
}