// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 訂單主檔
/// </summary>
public partial class OrdOrder
{
    /// <summary>
    /// 訂單編號
    /// </summary>
    public int OrderId { get; set; }

    /// <summary>
    /// 訂單號碼；唯一
    /// </summary>
    public string OrderNo { get; set; }

    /// <summary>
    /// 會員編號（FK）
    /// </summary>
    public int UserNumberId { get; set; }

    /// <summary>
    /// 訂單狀態（對照表後補）
    /// </summary>
    public string OrderStatusId { get; set; }

    /// <summary>
    /// 付款狀態：unpaid/paid/refunded…
    /// </summary>
    public string PaymentStatus { get; set; }

    /// <summary>
    /// 配送狀態（對照表後補）
    /// </summary>
    public string ShippingStatusId { get; set; }

    /// <summary>
    /// 小計金額
    /// </summary>
    public decimal Subtotal { get; set; }

    /// <summary>
    /// 優惠券（FK→MKT_Coupon）；可為 NULL
    /// </summary>
    public int? CouponId { get; set; }

    /// <summary>
    /// 折扣總額（= 所有調整合計；含品牌95折、券等）
    /// </summary>
    public decimal DiscountTotal { get; set; }

    /// <summary>
    /// 運費
    /// </summary>
    public decimal ShippingFee { get; set; }

    /// <summary>
    /// 付款方式（FK）
    /// </summary>
    public int PaymentConfigId { get; set; }

    /// <summary>
    /// 物流商名稱（FK→SUP_Logistics）
    /// </summary>
    public int? LogisticsId { get; set; }

    /// <summary>
    /// 收件人姓名
    /// </summary>
    public string ReceiverName { get; set; }

    /// <summary>
    /// 收件人電話；格式建議：數字/短橫線
    /// </summary>
    public string ReceiverPhone { get; set; }

    /// <summary>
    /// 收件人地址
    /// </summary>
    public string ReceiverAddress { get; set; }

    /// <summary>
    /// 是否有出貨標籤
    /// </summary>
    public bool HasShippingLabel { get; set; }

    /// <summary>
    /// 是否顯示給會員(風險管控)
    /// </summary>
    public bool IsVisibleToMember { get; set; }

    /// <summary>
    /// 建檔時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual MktCoupon Coupon { get; set; }

    public virtual SupLogistic Logistics { get; set; }

    public virtual ICollection<OrdInvoice> OrdInvoices { get; set; } = new List<OrdInvoice>();

    public virtual ICollection<OrdOrderAdjustment> OrdOrderAdjustments { get; set; } = new List<OrdOrderAdjustment>();

    public virtual ICollection<OrdOrderItemAdjustment> OrdOrderItemAdjustments { get; set; } = new List<OrdOrderItemAdjustment>();

    public virtual ICollection<OrdOrderItem> OrdOrderItems { get; set; } = new List<OrdOrderItem>();

    public virtual ICollection<OrdPayment> OrdPayments { get; set; } = new List<OrdPayment>();

    public virtual ICollection<OrdReturnItem> OrdReturnItems { get; set; } = new List<OrdReturnItem>();

    public virtual ICollection<OrdReturnRequest> OrdReturnRequests { get; set; } = new List<OrdReturnRequest>();

    public virtual ICollection<OrdShipping> OrdShippings { get; set; } = new List<OrdShipping>();

    public virtual OrdPaymentConfig PaymentConfig { get; set; }
}