// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 訂單層級折扣/調整（只支援 brand 與 coupon）
/// </summary>
public partial class OrdOrderAdjustment
{
    /// <summary>
    /// 調整主鍵
    /// </summary>
    public int AdjustmentId { get; set; }

    /// <summary>
    /// FK: Order
    /// </summary>
    public int OrderId { get; set; }

    /// <summary>
    /// 來源：coupon/brand/site/shipping/other
    /// </summary>
    public string Kind { get; set; }

    /// <summary>
    /// 範圍：order（全單）/brand（品牌）
    /// </summary>
    public string Scope { get; set; }

    /// <summary>
    /// Kind=brand 時必填(**串供應商表)
    /// </summary>
    public int? BrandId { get; set; }

    /// <summary>
    /// Kind=coupon 時必填(**串活動表)
    /// </summary>
    public int? CouponId { get; set; }

    /// <summary>
    /// 券碼或活動代碼（若有）
    /// </summary>
    public string Code { get; set; }

    /// <summary>
    /// 計算：percentage/fixed
    /// </summary>
    public string Method { get; set; }

    /// <summary>
    /// 比例；0.95=95折（**串供應商表）
    /// </summary>
    public decimal? DiscountRate { get; set; }

    /// <summary>
    /// 本筆訂單折扣金額（折扣為負值）
    /// </summary>
    public decimal AdjustmentAmount { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual SupBrand Brand { get; set; }

    public virtual MktCoupon Coupon { get; set; }

    public virtual OrdOrder Order { get; set; }
}