// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 付款方式設定
/// </summary>
public partial class OrdPaymentConfig
{
    /// <summary>
    /// 付款方式編號
    /// </summary>
    public int PaymentConfigId { get; set; }

    /// <summary>
    /// 付款方式代碼；允許NULL（建議 Filtered Unique）
    /// </summary>
    public string PaymentCode { get; set; }

    /// <summary>
    /// 付款方式名稱
    /// </summary>
    public string PaymentName { get; set; }

    public virtual ICollection<OrdOrder> OrdOrders { get; set; } = new List<OrdOrder>();

    public virtual ICollection<OrdPayment> OrdPayments { get; set; } = new List<OrdPayment>();
}