// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 配送明細
/// </summary>
public partial class OrdShipping
{
    /// <summary>
    /// 配送紀錄編號
    /// </summary>
    public int ShippingId { get; set; }

    /// <summary>
    /// 訂單編號（FK）
    /// </summary>
    public int OrderId { get; set; }

    /// <summary>
    /// 配送方式(**串物流組資料)
    /// </summary>
    public int LogisticsId { get; set; }

    /// <summary>
    /// 追蹤號碼
    /// </summary>
    public string TrackingNo { get; set; }

    /// <summary>
    /// 狀態（對照表後補）
    /// </summary>
    public int ShippingStatusId { get; set; }

    /// <summary>
    /// 備註
    /// </summary>
    public string Memo { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual SupLogistic Logistics { get; set; }

    public virtual OrdOrder Order { get; set; }
}