// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// SKU 與多個規格選項的對應
/// </summary>
public partial class ProdSkuSpecificationValue
{
    /// <summary>
    /// SKU ID（外鍵）
    /// </summary>
    public int SkuId { get; set; }

    /// <summary>
    /// 規格選項ID（外鍵）
    /// </summary>
    public int SpecificationOptionId { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime? CreatedDate { get; set; }

    public virtual ProdProductSku Sku { get; set; }

    public virtual ProdSpecificationOption SpecificationOption { get; set; }
}