// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 成分主檔，可被多個商品共用
/// </summary>
public partial class ProdIngredient
{
    /// <summary>
    /// 成分ID（主鍵）
    /// </summary>
    public int IngredientId { get; set; }

    /// <summary>
    /// 成分名稱
    /// </summary>
    public string IngredientName { get; set; }

    /// <summary>
    /// 別名或常見稱呼
    /// </summary>
    public string Alias { get; set; }

    /// <summary>
    /// 成分說明或注意事項
    /// </summary>
    public string Description { get; set; }

    public virtual ICollection<ProdProductIngredient> ProdProductIngredients { get; set; } = new List<ProdProductIngredient>();
}