// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 物流費率
/// </summary>
public partial class SupLogisticsRate
{
    /// <summary>
    /// 主鍵
    /// </summary>
    public int LogisticsRateId { get; set; }

    /// <summary>
    /// 關聯物流Id
    /// </summary>
    public int LogisticsId { get; set; }

    /// <summary>
    /// 最小重量 (kg)
    /// </summary>
    public decimal WeightMin { get; set; }

    /// <summary>
    /// 最大重量 (kg)，NULL=無限大
    /// </summary>
    public decimal? WeightMax { get; set; }

    /// <summary>
    /// 運費
    /// </summary>
    public decimal ShippingFee { get; set; }

    /// <summary>
    /// 是否啟用
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// 異動人員
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual SupLogistic Logistics { get; set; }
}