// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 庫存批次
/// </summary>
public partial class SupStockBatch
{
    /// <summary>
    /// 主鍵
    /// </summary>
    public int StockBatchId { get; set; }

    /// <summary>
    /// SKU ID (FK)
    /// </summary>
    public int SkuId { get; set; }

    /// <summary>
    /// 批號，唯一，非空
    /// </summary>
    public string BatchNumber { get; set; }

    /// <summary>
    /// 數量（CK ? 0）
    /// </summary>
    public int Qty { get; set; }

    /// <summary>
    /// 效期
    /// </summary>
    public DateOnly? ExpireDate { get; set; }

    /// <summary>
    /// 是否可銷售
    /// </summary>
    public bool IsSellable { get; set; }

    /// <summary>
    /// 建檔人員
    /// </summary>
    public int? Creator { get; set; }

    /// <summary>
    /// 建檔時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動人員
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual ProdProductSku Sku { get; set; }

    public virtual ICollection<SupStockHistory> SupStockHistories { get; set; } = new List<SupStockHistory>();
}