// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 系統代號檔
/// </summary>
public partial class SysCode
{
    /// <summary>
    /// 模組代號
    /// </summary>
    public string ModuleId { get; set; }

    /// <summary>
    /// 代號編碼
    /// </summary>
    public string CodeId { get; set; }

    /// <summary>
    /// 代號
    /// </summary>
    public string CodeNo { get; set; }

    /// <summary>
    /// 說明
    /// </summary>
    public string CodeDesc { get; set; }

    public string Memo { get; set; }

    /// <summary>
    /// 模組群組
    /// </summary>
    public string GroupName { get; set; }

    /// <summary>
    /// 程式代號
    /// </summary>
    public string ProgId { get; set; }

    /// <summary>
    /// 建檔人員
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 建檔時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 是否有效
    /// </summary>
    public bool IsActive { get; set; }
}