// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// SEO 設定表
/// </summary>
public partial class SysSeoMetum
{
    /// <summary>
    /// SEO 編號
    /// </summary>
    public int SeoId { get; set; }

    /// <summary>
    /// 來源表名稱
    /// </summary>
    public string RefTable { get; set; }

    /// <summary>
    /// 來源 ID
    /// </summary>
    public int RefId { get; set; }

    /// <summary>
    /// 頁面唯一 URL 標識
    /// </summary>
    public string SeoSlug { get; set; }

    /// <summary>
    /// SEO 標題簡稱
    /// </summary>
    public string SeoTitle { get; set; }

    /// <summary>
    /// SEO 簡短描述
    /// </summary>
    public string SeoDesc { get; set; }

    /// <summary>
    /// 建檔時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual ICollection<CntPage> CntPages { get; set; } = new List<CntPage>();

    public virtual ICollection<ProdProductTypeConfig> ProdProductTypeConfigs { get; set; } = new List<ProdProductTypeConfig>();

    public virtual ICollection<ProdProduct> ProdProducts { get; set; } = new List<ProdProduct>();

    public virtual ICollection<SupBrand> SupBrands { get; set; } = new List<SupBrand>();

    public virtual ICollection<SysSeoMetaAsset> SysSeoMetaAssets { get; set; } = new List<SysSeoMetaAsset>();
}