// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 角色擁有的模組權限
/// </summary>
public partial class UserRoleModule
{
    /// <summary>
    /// 主鍵 ID
    /// </summary>
    public int RoleModuleId { get; set; }

    /// <summary>
    /// 管理員角色 ID (FK)
    /// </summary>
    public string AdminRoleId { get; set; }

    /// <summary>
    /// 模組代號
    /// </summary>
    public string ModuleId { get; set; }

    /// <summary>
    /// 建檔人員
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 建立時間 (UTC)
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動人員
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間 (UTC)
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual AspNetRole AdminRole { get; set; }
}