// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 會員等級設定
/// </summary>
public partial class UserMemberRank
{
    /// <summary>
    /// 等級代碼
    /// </summary>
    public string MemberRankId { get; set; }

    /// <summary>
    /// 等級名稱
    /// </summary>
    public string RankName { get; set; }

    /// <summary>
    /// 升級所需總消費金額
    /// </summary>
    public decimal TotalSpentForUpgrade { get; set; }

    /// <summary>
    /// 升級所需訂單數
    /// </summary>
    public int OrderCountForUpgrade { get; set; }

    /// <summary>
    /// 回饋率
    /// </summary>
    public decimal RebateRate { get; set; }

    /// <summary>
    /// 等級說明
    /// </summary>
    public string RankDescription { get; set; }

    /// <summary>
    /// 是否啟用
    /// </summary>
    public bool IsActive { get; set; }
}