// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 會員禁用紀錄
/// </summary>
public partial class UserBlockHistory
{
    /// <summary>
    /// 禁用紀錄 ID
    /// </summary>
    public int BlockHistoryId { get; set; }

    /// <summary>
    /// 會員 ID
    /// </summary>
    public int UserNumberId { get; set; }

    /// <summary>
    /// 禁用原因
    /// </summary>
    public string Reason { get; set; }

    /// <summary>
    /// 禁用範圍
    /// </summary>
    public string Scope { get; set; }

    /// <summary>
    /// 開始日期
    /// </summary>
    public DateOnly StartDate { get; set; }

    /// <summary>
    /// 結束日期
    /// </summary>
    public DateOnly? EndDate { get; set; }

    /// <summary>
    /// 禁用狀態
    /// </summary>
    public string Status { get; set; }

    /// <summary>
    /// 設定者
    /// </summary>
    public int? Creator { get; set; }

    /// <summary>
    /// 異動者
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }
}