// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 會員擁有的優惠券錢包
/// </summary>
public partial class UserCouponWallet
{
    /// <summary>
    /// 會員優惠券 ID
    /// </summary>
    public int CouponWalletId { get; set; }

    /// <summary>
    /// 會員 ID
    /// </summary>
    public int UserNumberId { get; set; }

    /// <summary>
    /// 優惠券id
    /// </summary>
    public int CouponId { get; set; }

    /// <summary>
    /// 領取時間
    /// </summary>
    public DateTime ClaimedDate { get; set; }

    /// <summary>
    /// 使用時間
    /// </summary>
    public DateTime? UsedDate { get; set; }

    /// <summary>
    /// 使用狀態
    /// </summary>
    public string Status { get; set; }

    public virtual MktCoupon Coupon { get; set; }
}