// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Infra.Models;

/// <summary>
/// 商品的規格設定的選項
/// </summary>
public partial class ProdSpecificationOptionDto
{
    /// <summary>
    /// 規格選項ID（主鍵）
    /// </summary>
    public int SpecificationOptionId { get; set; }

    /// <summary>
    /// SKU ID（外鍵）
    /// </summary>
    public int SkuId { get; set; }

    /// <summary>
    /// 規格群組ID（外鍵）
    /// </summary>
    public int SpecificationConfigId { get; set; }

    /// <summary>
    /// 規格選項名稱（例如：250ml、巧克力）
    /// </summary>
    public string OptionName { get; set; }
}