// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.Core.DTOs.PROD;

/// <summary>
/// SKU層級與即時庫存(支援多規格)
/// </summary>
public partial class ProdProductSkuDto
{
    /// <summary>
    /// SKU ID（主鍵）
    /// </summary>
    public int SkuId { get; set; }

    /// <summary>
    /// 規格碼
    /// </summary>
    public string SpecCode { get; set; }

    /// <summary>
    /// SKU代碼
    /// </summary>
    public string SkuCode { get; set; }

    /// <summary>
    /// 商品ID（外鍵）
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// 條碼
    /// </summary>
    public string Barcode { get; set; }

    /// <summary>
    /// 成本價
    /// </summary>
    public decimal? CostPrice { get; set; }

    /// <summary>
    /// 原價
    /// </summary>
    public decimal? ListPrice { get; set; }

    /// <summary>
    /// 單價
    /// </summary>
    public decimal? UnitPrice { get; set; }

    /// <summary>
    /// 優惠價
    /// </summary>
    public decimal SalePrice { get; set; }

    /// <summary>
    /// 目前庫存
    /// </summary>
    public int StockQty { get; set; }

    /// <summary>
    /// 安全庫存量（低於提醒）
    /// </summary>
    public int SafetyStockQty { get; set; }

    /// <summary>
    /// 再訂購點（≧安全庫存量）
    /// </summary>
    public int ReorderPoint { get; set; }

    /// <summary>
    /// 最大庫存量（0=不限制)
    /// </summary>
    public int MaxStockQty { get; set; }

    /// <summary>
    /// 是否允許缺貨預購（1=可超賣，0=禁止）
    /// </summary>
    public bool IsAllowBackorder { get; set; }

    public int ShelfLifeDays { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }
}