// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 文章/課程購買紀錄
/// </summary>
public partial class CntPurchase
{
    /// <summary>
    /// 購買紀錄 ID
    /// </summary>
    public int PurchaseId { get; set; }

    /// <summary>
    /// 會員 ID
    /// </summary>
    public int UserNumberId { get; set; }

    /// <summary>
    /// 文章/課程 ID
    /// </summary>
    public int PageId { get; set; }

    /// <summary>
    /// 是否購買（0=未購買，1=已購買）
    /// </summary>
    public bool IsPaid { get; set; }

    /// <summary>
    /// 單價
    /// </summary>
    public decimal UnitPrice { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual CntPage Page { get; set; }
}