// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// FAQ 搜尋關鍵字
/// </summary>
public partial class CsFaqKeyword
{
    /// <summary>
    /// 主鍵
    /// </summary>
    public int KeywordId { get; set; }

    /// <summary>
    /// 對應 FAQ
    /// </summary>
    public int FaqId { get; set; }

    /// <summary>
    /// 關鍵字／同義詞
    /// </summary>
    public string Keyword { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    public virtual CsFaq Faq { get; set; }
}