// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 廣告紀錄
/// </summary>
public partial class MktAdLog
{
    /// <summary>
    /// 紀錄編號
    /// </summary>
    public int LogId { get; set; }

    /// <summary>
    /// 廣告編號
    /// </summary>
    public int AdId { get; set; }

    /// <summary>
    /// 事件類型（impression/click）
    /// </summary>
    public string EventType { get; set; }

    /// <summary>
    /// 使用者IP
    /// </summary>
    public string UserIp { get; set; }

    /// <summary>
    /// 發生時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    public virtual MktAd Ad { get; set; }
}