// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 廣告位置
/// </summary>
public partial class MktPlacement
{
    /// <summary>
    /// 位置編號
    /// </summary>
    public int PlacementId { get; set; }

    /// <summary>
    /// 位置名稱
    /// </summary>
    public string PlacementName { get; set; }

    /// <summary>
    /// 位置說明
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// 建議尺寸
    /// </summary>
    public string Size { get; set; }

    /// <summary>
    /// 顯示順序
    /// </summary>
    public int OrderSeq { get; set; }

    /// <summary>
    /// 是否啟用（0=否，1=是）
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// 異動人員
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual ICollection<MktAdPlacementMap> MktAdPlacementMap { get; set; } = new List<MktAdPlacementMap>();
}