// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 綠界付款結果通知
/// </summary>
public partial class OrdEcpayReturnNotification
{
    /// <summary>
    /// 通知ID
    /// </summary>
    public int NotificationId { get; set; }

    /// <summary>
    /// 接收時間
    /// </summary>
    public DateTime ReceivedDate { get; set; }

    /// <summary>
    /// 特店編號
    /// </summary>
    public string MerchantId { get; set; }

    /// <summary>
    /// 平台商編號
    /// </summary>
    public string PlatformId { get; set; }

    /// <summary>
    /// 分店代號
    /// </summary>
    public string StoreId { get; set; }

    /// <summary>
    /// 我方訂單編號；允許NULL
    /// </summary>
    public string MerchantTradeNo { get; set; }

    /// <summary>
    /// 綠界交易編號；全域唯一；Payment 以此關聯
    /// </summary>
    public string TradeNo { get; set; }

    /// <summary>
    /// 回應代碼
    /// </summary>
    public int RtnCode { get; set; }

    /// <summary>
    /// 回應訊息
    /// </summary>
    public string RtnMsg { get; set; }

    /// <summary>
    /// 交易金額(元)；整數
    /// </summary>
    public int TradeAmt { get; set; }

    /// <summary>
    /// 付款方式
    /// </summary>
    public string PaymentType { get; set; }

    /// <summary>
    /// 通道手續費
    /// </summary>
    public decimal? PaymentTypeChargeFee { get; set; }

    /// <summary>
    /// 交易建立時間（yyyy/MM/dd HH:mm:ss）
    /// </summary>
    public DateTime TradeDate { get; set; }

    /// <summary>
    /// 付款完成時間（成功時才有）
    /// </summary>
    public DateTime? PaymentDate { get; set; }

    /// <summary>
    /// 模擬付款
    /// </summary>
    public bool? SimulatePaid { get; set; }

    public string CustomField1 { get; set; }

    public string CustomField2 { get; set; }

    public string CustomField3 { get; set; }

    public string CustomField4 { get; set; }

    /// <summary>
    /// 驗簽值
    /// </summary>
    public string CheckMacValue { get; set; }

    /// <summary>
    /// 原始本文（表單/JSON）
    /// </summary>
    public string RawBody { get; set; }

    /// <summary>
    /// 原始標頭（選填）
    /// </summary>
    public string RawHeaders { get; set; }

    /// <summary>
    /// 失敗原因(optional)
    /// </summary>
    public string FailReason { get; set; }
}