// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 商品分類設定檔，可支援多階層架構
/// </summary>
public partial class ProdProductTypeConfig
{
    /// <summary>
    /// 分類ID（主鍵）
    /// </summary>
    public int ProductTypeId { get; set; }

    /// <summary>
    /// 父分類ID（NULL 代表最上層）
    /// </summary>
    public int? ParentId { get; set; }

    /// <summary>
    /// 分類名稱
    /// </summary>
    public string ProductTypeName { get; set; }

    /// <summary>
    /// Seo 設定
    /// </summary>
    public int? SeoId { get; set; }

    /// <summary>
    /// 顯示順序
    /// </summary>
    public int OrderSeq { get; set; }

    /// <summary>
    /// 是否啟用分類（0=否，1=是）
    /// </summary>
    public bool IsActive { get; set; }

    public virtual ICollection<ProdProductTypeConfig> InverseParent { get; set; } = new List<ProdProductTypeConfig>();

    public virtual ProdProductTypeConfig Parent { get; set; }

    public virtual ICollection<ProdProductType> ProdProductType { get; set; } = new List<ProdProductType>();

    public virtual SysSeoMeta Seo { get; set; }
}