// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 以某一個「主商品」作為套組對外銷售，內容由多個子商品組成
/// </summary>
public partial class ProdBundle
{
    /// <summary>
    /// 套組ID（主鍵）
    /// </summary>
    public int BundleId { get; set; }

    /// <summary>
    /// 組合商品Id
    /// </summary>
    public int SubProductId { get; set; }

    /// <summary>
    /// 套組名稱
    /// </summary>
    public string BundleName { get; set; }

    /// <summary>
    /// 是否啟用
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// 建檔人員
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動人員
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual ProdProduct SubProduct { get; set; }
}