// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 會員對商品的收藏（我的最愛）紀錄
/// </summary>
public partial class ProdProductFavorite
{
    /// <summary>
    /// 商品ID（外鍵）
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// 會員ID（外鍵）
    /// </summary>
    public int UserNumberId { get; set; }

    /// <summary>
    /// 加入最愛時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    public virtual ProdProduct Product { get; set; }
}