// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 商品與SKU的圖片管理；主圖唯一；順序可控
/// </summary>
public partial class ProdProductImage
{
    /// <summary>
    /// 圖片ID（主鍵）
    /// </summary>
    public int ImageId { get; set; }

    /// <summary>
    /// 商品ID（外鍵）
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// 若圖片只屬於特定SKU（如顏色/口味），可繫結SKU
    /// </summary>
    public int? SkuId { get; set; }

    /// <summary>
    /// 商品圖片
    /// </summary>
    public int? ImgId { get; set; }

    /// <summary>
    /// 是否為主圖（1=主圖）
    /// </summary>
    public bool IsMain { get; set; }

    /// <summary>
    /// 顯示順序
    /// </summary>
    public int OrderSeq { get; set; }

    /// <summary>
    /// 上傳時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    public virtual SysAssetFile Img { get; set; }

    public virtual ProdProduct Product { get; set; }

    public virtual ProdProductSku Sku { get; set; }
}