// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 商品/SKU 的會員評價與圖片；建議搭配審核機制
/// </summary>
public partial class ProdProductReview
{
    /// <summary>
    /// 評價ID（主鍵）
    /// </summary>
    public int ReviewId { get; set; }

    /// <summary>
    /// 商品ID（外鍵）
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// 若評價針對特定SKU（口味/容量等），可繫結SKU
    /// </summary>
    public int? SkuId { get; set; }

    /// <summary>
    /// 評論會員ID（外鍵）
    /// </summary>
    public int UserNumberId { get; set; }

    /// <summary>
    /// 星等（1~5）
    /// </summary>
    public byte Rating { get; set; }

    /// <summary>
    /// 評價標題
    /// </summary>
    public string Title { get; set; }

    /// <summary>
    /// 評價內容
    /// </summary>
    public string Content { get; set; }

    /// <summary>
    /// 是否通過審核（防刷評）
    /// </summary>
    public bool IsApproved { get; set; }

    /// <summary>
    /// 評論時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 最後更新時間（編輯時更新）
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual ICollection<ProdProductReviewImage> ProdProductReviewImage { get; set; } = new List<ProdProductReviewImage>();

    public virtual ProdProduct Product { get; set; }

    public virtual ProdProductSku Sku { get; set; }
}