// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 品牌文章內容表
/// </summary>
public partial class SupBrandArticle
{
    /// <summary>
    /// 主鍵
    /// </summary>
    public int ContentId { get; set; }

    /// <summary>
    /// 關聯品牌Id
    /// </summary>
    public int? BrandId { get; set; }

    /// <summary>
    /// 文章圖片
    /// </summary>
    public int? ImgId { get; set; }

    /// <summary>
    /// 內容標題
    /// </summary>
    public string ContentTitle { get; set; }

    /// <summary>
    /// 內文（支援HTML）
    /// </summary>
    public string Content { get; set; }

    /// <summary>
    /// 類型：文章/公告/新聞/活動
    /// </summary>
    public string ContentType { get; set; }

    /// <summary>
    /// 顯示順序
    /// </summary>
    public int OrderSeq { get; set; }

    /// <summary>
    /// 是否啟用
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// 發布時間，可排程
    /// </summary>
    public DateTime? PublishDate { get; set; }

    /// <summary>
    /// 建檔人員
    /// </summary>
    public int? Creator { get; set; }

    /// <summary>
    /// 建檔時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 異動人員
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }

    public virtual SupBrand Brand { get; set; }

    public virtual SysAssetFile Img { get; set; }
}