// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 通用媒體庫（圖片/影片/檔案）
/// </summary>
public partial class SysAssetFile
{
    /// <summary>
    /// 主鍵 ID
    /// </summary>
    public int FileId { get; set; }

    /// <summary>
    /// 雜湊或GUID，用來防重複
    /// </summary>
    public string FileKey { get; set; }

    /// <summary>
    /// 是否外部URL
    /// </summary>
    public bool IsExternal { get; set; }

    /// <summary>
    /// 完整URL或相對路徑
    /// </summary>
    public string FileUrl { get; set; }

    /// <summary>
    /// 副檔名，例如 jpg, png, webp
    /// </summary>
    public string FileExt { get; set; }

    /// <summary>
    /// image/jpeg, image/png, video/mp4
    /// </summary>
    public string MimeType { get; set; }

    /// <summary>
    /// 影像寬度（非影像類型可為 NULL）
    /// </summary>
    public int? Width { get; set; }

    /// <summary>
    /// 影像高度（非影像類型可為 NULL）
    /// </summary>
    public int? Height { get; set; }

    /// <summary>
    /// 檔案大小（byte 為單位）
    /// </summary>
    public long? FileSizeBytes { get; set; }

    /// <summary>
    /// Alt 替代文字
    /// </summary>
    public string AltText { get; set; }

    /// <summary>
    /// 文字說明 / 附註文字
    /// </summary>
    public string Caption { get; set; }

    /// <summary>
    /// 建檔時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 是否有效
    /// </summary>
    public bool IsActive { get; set; }

    public virtual ICollection<CntMedia> CntMedia { get; set; } = new List<CntMedia>();

    public virtual ICollection<CntPageBlock> CntPageBlock { get; set; } = new List<CntPageBlock>();

    public virtual ICollection<MktAd> MktAd { get; set; } = new List<MktAd>();

    public virtual ICollection<MktCampaign> MktCampaign { get; set; } = new List<MktCampaign>();

    public virtual ICollection<OrdReturnRequest> OrdReturnRequest { get; set; } = new List<OrdReturnRequest>();

    public virtual ICollection<ProdProductImage> ProdProductImage { get; set; } = new List<ProdProductImage>();

    public virtual ICollection<ProdProductReviewImage> ProdProductReviewImage { get; set; } = new List<ProdProductReviewImage>();

    public virtual ICollection<SupBrandAccordionContent> SupBrandAccordionContent { get; set; } = new List<SupBrandAccordionContent>();

    public virtual ICollection<SupBrandArticle> SupBrandArticle { get; set; } = new List<SupBrandArticle>();

    public virtual ICollection<SysSeoMetaAsset> SysSeoMetaAsset { get; set; } = new List<SysSeoMetaAsset>();
}