// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 信用卡付款資訊
/// </summary>
public partial class UserCreditCardInfo
{
    /// <summary>
    /// 信用卡資訊 ID
    /// </summary>
    public int CreditCardInfoId { get; set; }

    /// <summary>
    /// 付款方式 ID
    /// </summary>
    public int PaymentMethodId { get; set; }

    /// <summary>
    /// 信用卡品牌
    /// </summary>
    public string CardBrand { get; set; }

    /// <summary>
    /// 卡號末四碼
    /// </summary>
    public string CardLastFourDigits { get; set; }

    /// <summary>
    /// 有效期限
    /// </summary>
    public string ExpiryDate { get; set; }

    public virtual UserMemberPaymentMethod PaymentMethod { get; set; }
}