// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FlexBackend.CNT.Rcl.Models;

/// <summary>
/// 會員通知設定
/// </summary>
public partial class UserNotification
{
    /// <summary>
    /// 通知設定 ID
    /// </summary>
    public int NotificationId { get; set; }

    /// <summary>
    /// 會員 ID
    /// </summary>
    public int UserNumberId { get; set; }

    /// <summary>
    /// 通知類型
    /// </summary>
    public string NotificationType { get; set; }

    /// <summary>
    /// 啟用狀態
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// 建檔人員 ID
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 異動人員 ID
    /// </summary>
    public int? Reviser { get; set; }

    /// <summary>
    /// 異動時間
    /// </summary>
    public DateTime? RevisedDate { get; set; }
}