// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Reflection;
using tHerdBackend.Core.ValueObjects;

namespace tHerdBackend.Core.DTOs;

/// <summary>
/// 通用媒體庫（圖片/影片/檔案）
/// </summary>
public partial class SysAssetFileDto
{
    /// <summary>
    /// 主鍵 ID
    /// </summary>
    public int FileId { get; set; }

    /// <summary>
    /// 雜湊或GUID，用來防重複
    /// </summary>
    public string FileKey { get; set; }

    /// <summary>
    /// 是否外部URL
    /// </summary>
    public bool IsExternal { get; set; }

    /// <summary>
    /// 完整URL或相對路徑
    /// </summary>
    public string FileUrl { get; set; }

    /// <summary>
    /// 副檔名，例如 jpg, png, webp
    /// </summary>
    public string FileExt { get; set; }

    /// <summary>
    /// image/jpeg, image/png, video/mp4
    /// </summary>
    public string MimeType { get; set; }

    /// <summary>
    /// 影像寬度（非影像類型可為 NULL）
    /// </summary>
    public int? Width { get; set; }

    /// <summary>
    /// 影像高度（非影像類型可為 NULL）
    /// </summary>
    public int? Height { get; set; }

    /// <summary>
    /// 檔案大小（byte 為單位）
    /// </summary>
    public long? FileSizeBytes { get; set; }

    /// <summary>
    /// Alt 替代文字
    /// </summary>
    public string? AltText { get; set; } = "";

    /// <summary>
    /// 文字說明 / 附註文字
    /// </summary>
    public string? Caption { get; set; } = "";

    /// <summary>
    /// 建檔時間
    /// </summary>
    public DateTime CreatedDate { get; set; }

    public string FormateCreatedDate => DateTimeHelper.ToDateTimeString(CreatedDate);

    /// <summary>
    /// 是否有效
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// 關聯資料夾 ID
    /// </summary>
    public int? FolderId { get; set; }

    /// <summary>
    /// 該檔案的階層（根 → 子 → ...）
    /// </summary>
    public List<FolderLevelItem> FolderPaths { get; set; } = new();

    /// <summary>
    /// 前端實際可載入的網址（會自動判斷內外部）
    /// </summary>
    public string PublicUrl =>
        string.IsNullOrWhiteSpace(FileUrl)
            ? "/images/No-Image.svg"
            : (IsExternal || FileUrl.StartsWith("http", StringComparison.OrdinalIgnoreCase)
                ? FileUrl
                : $"/Images/{Path.GetFileName(FileUrl)}");
}

/// <summary>
/// 階層資料結構
/// </summary>
public class FolderLevelItem
{
    public int Seq { get; set; }        // 階層序號（0 = 根）
    public string Folder { get; set; } = string.Empty; // 資料夾名稱
}

/// <summary>
/// 上傳檔案 DTO
/// </summary>
public class AssetFileUploadDto
{
    public string ModuleId { get; set; } // 模組代號
    public string ProgId { get; set; } // 程式代號
    public int? FolderId { get; set; }
    public bool IsExternal { get; set; } = true; // T: 雲端; F: 本地
    public List<AssetFileDetailsDto> Meta { get; set; } = new();
}

/// <summary>
/// 上傳檔案明細
/// </summary>
public class AssetFileDetailsDto
{
    public IFormFile File { get; set; } = default!;
    public string? AltText { get; set; }
    public string? Caption { get; set; }
    public bool IsActive { get; set; } = true;
    public string? FileUrl { get; set; }
}

/// <summary>
/// 專供前端傳入 _FileListPartial 使用的輕量版 DTO
/// </summary>
public class SimpleAssetFileDto
{
    public int FileId { get; set; }
    public string FileUrl { get; set; }
    public string MimeType { get; set; }
    public string AltText { get; set; }
    public string Caption { get; set; }
    public bool IsActive { get; set; }
}